// A script to print all the ngrok/Prod links for templatization
package main

import "fmt"

var pages = map[string]string{
	"learn-more": "learn-more",

	// competitors
	"aiapply-alternative":                 "aiapply-alternative",
	"lazyapply-alternative":               "lazyapply-alternative",
	"loopcv-alternative":                  "loopcv-alternative",
	"sonara-alternative":                  "sonara-alternative",
	"usemassive-alternative":              "usemassive-alternative",
	"earnbetter-alternative":              "earnbetter-alternative",
	"instaapply-alternative":              "instaapply-alternative",
	"easyapply-alternative":               "easyapply-alternative",
	"simplify-alternative":                "simplify-alternative",
	"applyre-alternative":                 "applyre-alternative",
	"applyhero-alternative":               "applyhero-alternative",
	"jobs-aicopilot-alternative":          "jobs-aicopilot-alternative",
	"autojob-alternative":                 "autojob-alternative",
	"injob-ai-alternative":                "injob-ai-alternative",
	"flashapply-alternative":              "flashapply-alternative",
	"jobwizard-alternative":               "jobwizard-alternative",
	"jobs-scout-alternative":              "jobs-scout-alternative",
	"instantapply-alternative":            "instantapply-alternative",
	"algojobsca-alternative":              "algojobsca-alternative",
	"powerapply-alternative":              "powerapply-alternative",
	"myresumehero-alternative":            "myresumehero-alternative",
	"apply-engine-ai-alternative":         "apply-engine-ai-alternative",
	"applai-alternative":                  "applai-alternative",
	"ezyapply-alternative":                "ezyapply-alternative",
	"resumefox-alternative":               "resumefox-alternative",
	"tuilink-alternative":                 "tuilink-alternative",
	"jobsolv-alternative":                 "jobsolv-alternative",
	"shinobi-alternative":                 "shinobi-alternative",
	"jobrpro-alternative":                 "jobrpro-alternative",
	"resumedwork-alternative":             "resumedwork-alternative",
	"magicresume-alternative":             "magicresume-alternative",
	"echotalent-alternative":              "echotalent-alternative",
	"reppls-alternative":                  "reppls-alternative",
	"job-right-alternative":               "job-right-alternative",
	"majorgen-alternative":                "majorgen-alternative",
	"resufit-alternative":                 "resufit-alternative",
	"jobhunnt-alternative":                "jobhunnt-alternative",
	"applypro-alternative":                "applypro-alternative",
	"grabtie-alternative":                 "grabtie-alternative",
	"swooped-alternative":                 "swooped-alternative",
	"get-hired-yesterday-alternative":     "get-hired-yesterday-alternative",
	"build-me-a-cover-letter-alternative": "build-me-a-cover-letter-alternative",
	"career-tool-belt-alternative":        "career-tool-belt-alternative",
	"canyon-alternative":                  "canyon-alternative",
	"resumegenerator-alternative":         "resumegenerator-alternative",
	"tealhq-alternative":                  "tealhq-alternative",
	"mployee-alternative":                 "mployee-alternative",
	"jobtatkal-alternative":               "jobtatkal-alternative",
	"final-round-ai-alternative":          "final-round-ai-alternative",
	"jobs-pikr-alternative":               "jobs-pikr-alternative",
	"jobalytics-alternative":              "jobalytics-alternative",
	"i-got-an-offer-alternative":          "i-got-an-offer-alternative",
	"intoo-alternative":                   "intoo-alternative",
	"jobiffy-alternative":                 "jobiffy-alternative",
	"bulk-apply-alternative":              "bulk-apply-alternative",
	"the-ladders-alternative":             "the-ladders-alternative",

	// industry specific
	"ai-ml-jobs":        "ai-ml-jobs",
	"consulting-jobs":   "consulting-jobs",
	"cyber-jobs":        "cyber-jobs",
	"data-science-jobs": "data-science-jobs",
	"finance-jobs":      "finance-jobs",
	"healthcare-jobs":   "healthcare-jobs",
	"marketing-jobs":    "marketing-jobs",
	"tech-jobs":         "tech-jobs",

	// career stage specific
	"director-level-jobs":  "director-level-jobs",
	"entry-level-jobs":     "entry-level-jobs",
	"executive-jobs":       "executive-jobs",
	"fresh-grad-jobs":      "fresh-grad-jobs",
	"mid-career-jobs":      "mid-career-jobs",
	"senior-software-jobs": "senior-software-jobs",

	// location specific
	"f1-opt-jobs":                 "f1-opt-jobs",
	"h1b-visa-jobs":               "h1b-visa-jobs",
	"international-students-jobs": "international-students-jobs",
	"jobs-in-new-york":            "jobs-in-new-york",
	"jobs-in-sf":                  "jobs-in-sf",
	"jobs-in-san-francisco":       "jobs-in-san-francisco",
	"remote-jobs":                 "remote-jobs",
	"texas-jobs":                  "texas-jobs",
	"jobs-in-texas":               "jobs-in-texas",

	// pain point specific
	"ats-friendly-resume-service":               "ats-friendly-resume-service",
	"automated-job-application-service":         "automated-job-application-service",
	"how-to-get-more-interview-calls":           "how-to-get-more-interview-calls",
	"job-application-burnout-solution":          "job-application-burnout-solution",
	"job-search-taking-too-long":                "job-search-taking-too-long",
	"no-response-for-job-applications":          "no-response-for-job-applications",
	"too-busy-to-apply-for-jobs":                "too-busy-to-apply-for-jobs",
	"why-jobs-applications-are-not-working":     "why-jobs-applications-are-not-working",
	"why-job-applications-are-not-shortlisting": "why-job-applications-are-not-shortlisting",

	// competitive positioning pages
	"alternative-to-apply-yourself":           "alternative-to-apply-yourself",
	"automated-vs-human-job-application":      "automated-vs-human-job-application",
	"best-job-application-service-2025":       "best-job-application-service-2025",
	"job-application-service-comparision":     "job-application-service-comparision",
	"scale-jobs-vs-career-coach":              "scale-jobs-vs-career-coach",
	"scale-jobs-vs-linkedin-easy-apply":       "scale-jobs-vs-linkedin-easy-apply",
	"scale-jobs-vs-traditional-recruiter":     "scale-jobs-vs-traditional-recruiter",
	"staffing-agenecy-vs-application-service": "staffing-agenecy-vs-application-service",

	// success story focused
	"93%-placement-success":                   "93%-placement-success",
	"average-job-search-time-reduction":       "average-job-search-time-reduction",
	"career-change-success-stories":           "career-change-success-stories",
	"h1b-visa-job-placement-stories":          "h1b-visa-job-placement-stories",
	"international-students-job-success":      "international-students-job-success",
	"job-search-success-stories-2025":         "job-search-success-stories-2025",
	"salary-increase-through-multiple-offers": "salary-increase-through-multiple-offers",
	"tech-layoff-recovery-stories":            "tech-layoff-recovery-stories",

	// authority building pages
	"applicaiton-volume-success-stories-correlation": "applicaiton-volume-success-stories-correlation",
	"ats-system-optimisation-guide":                  "ats-system-optimisation-guide",
	"best-time-to-apply":                             "best-time-to-apply",
	"how-many-applications-to-get-job":               "how-many-applications-to-get-job",
	"job-application-response-rate":                  "job-application-response-rate",
	"job-search-timeline":                            "job-search-timeline",
	"salary-negotiation-with-multiple-offers":        "salary-negotiation-with-multiple-offers",

	// time sensitive pages
	"back-to-work-after-layoff":        "back-to-work-after-layoff",
	"economic-uncertainty-job-search":  "economic-uncertainty-job-search",
	"holiday-season-jobs":              "holiday-season-jobs",
	"job-search-during-recession-2025": "job-search-during-recession-2025",
	"new-year-job-search-strategy":     "new-year-job-search-strategy",
	"post-graduation-job-hunt-2025":    "post-graduation-job-hunt-2025",
	"q1-hiring-season-optimization":    "q1-hiring-season-optimization",
	"tech-layoff-job-search":           "tech-layoff-job-search",

	// landing pages
	"land-your-first-job-in-usa": "land-your-first-job-in-usa",
}

var orderedIDs = []string{
	"learn-more",
	"aiapply-alternative",
	"lazyapply-alternative",
	"loopcv-alternative",
	"sonara-alternative",
	"usemassive-alternative",
	"earnbetter-alternative",
	"instaapply-alternative",
	"easyapply-alternative",
	"simplify-alternative",
	"applyre-alternative",
	"applyhero-alternative",
	"jobs-aicopilot-alternative",
	"autojob-alternative",
	"injob-ai-alternative",
	"flashapply-alternative",
	"jobwizard-alternative",
	"jobs-scout-alternative",
	"instantapply-alternative",
	"algojobsca-alternative",
	"powerapply-alternative",
	"myresumehero-alternative",
	"apply-engine-ai-alternative",
	"applai-alternative",
	"ezyapply-alternative",
	"resumefox-alternative",
	"tuilink-alternative",
	"jobsolv-alternative",
	"shinobi-alternative",
	"jobrpro-alternative",
	"resumedwork-alternative",
	"magicresume-alternative",
	"echotalent-alternative",
	"reppls-alternative",
	"job-right-alternative",
	"majorgen-alternative",
	"resufit-alternative",
	"jobhunnt-alternative",
	"applypro-alternative",
	"grabtie-alternative",
	"swooped-alternative",
	"get-hired-yesterday-alternative",
	"build-me-a-cover-letter-alternative",
	"career-tool-belt-alternative",
	"canyon-alternative",
	"resumegenerator-alternative",
	"tealhq-alternative",
	"mployee-alternative",
	"jobtatkal-alternative",
	"final-round-ai-alternative",
	"jobs-pikr-alternative",
	"jobalytics-alternative",
	"i-got-an-offer-alternative",
	"intoo-alternative",
	"jobiffy-alternative",
	"bulk-apply-alternative",
	"the-ladders-alternative",
	"ai-ml-jobs",
	"consulting-jobs",
	"cyber-jobs",
	"data-science-jobs",
	"finance-jobs",
	"healthcare-jobs",
	"marketing-jobs",
	"tech-jobs",
	"director-level-jobs",
	"entry-level-jobs",
	"executive-jobs",
	"fresh-grad-jobs",
	"mid-career-jobs",
	"senior-software-jobs",
	"f1-opt-jobs",
	"h1b-visa-jobs",
	"international-students-jobs",
	"jobs-in-new-york",
	"jobs-in-sf",
	"jobs-in-san-francisco",
	"remote-jobs",
	"texas-jobs",
	"jobs-in-texas",
	"ats-friendly-resume-service",
	"automated-job-application-service",
	"how-to-get-more-interview-calls",
	"job-application-burnout-solution",
	"job-search-taking-too-long",
	"no-response-for-job-applications",
	"too-busy-to-apply-for-jobs",
	"why-jobs-applications-are-not-working",
	"why-job-applications-are-not-shortlisting",
	"alternative-to-apply-yourself",
	"automated-vs-human-job-application",
	"best-job-application-service-2025",
	"job-application-service-comparision",
	"scale-jobs-vs-career-coach",
	"scale-jobs-vs-linkedin-easy-apply",
	"scale-jobs-vs-traditional-recruiter",
	"staffing-agenecy-vs-application-service",
	"93%-placement-success",
	"average-job-search-time-reduction",
	"career-change-success-stories",
	"h1b-visa-job-placement-stories",
	"international-students-job-success",
	"job-search-success-stories-2025",
	"salary-increase-through-multiple-offers",
	"tech-layoff-recovery-stories",
	"applicaiton-volume-success-stories-correlation",
	"ats-system-optimisation-guide",
	"best-time-to-apply",
	"how-many-applications-to-get-job",
	"job-application-response-rate",
	"job-search-timeline",
	"salary-negotiation-with-multiple-offers",
	"back-to-work-after-layoff",
	"economic-uncertainty-job-search",
	"holiday-season-jobs",
	"job-search-during-recession-2025",
	"new-year-job-search-strategy",
	"post-graduation-job-hunt-2025",
	"q1-hiring-season-optimization",
	"tech-layoff-job-search",
	"land-your-first-job-in-usa",
}

func main() {
	for i, id := range orderedIDs {
		fmt.Printf("%d. https://3979eadc38a9.ngrok-free.app/%s\n", i+1, pages[id])
	}
}
